// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kolobok-kelbek/tomato/infra"
	"github.com/kolobok-kelbek/tomato/infra/config"
	"github.com/kolobok-kelbek/tomato/infra/logger"
	"github.com/kolobok-kelbek/tomato/static"
)

// Injectors from wire.go:

func Init() *infra.App {
	fs := _wireFSValue
	configConfig := config.Load(fs)
	sugaredLogger := logger.NewLogger()
	app := infra.NewApp(configConfig, sugaredLogger)
	return app
}

var (
	_wireFSValue = static.Snapshot
)
